version: "3.1"

services:
  db:
    image: postgres
    container_name: "eldenring"
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
